[2023-10-09T21:13:18.900+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_data_pipeline.scrape_video_list manual__2023-10-09T21:13:14.360072+00:00 [queued]>
[2023-10-09T21:13:18.988+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_data_pipeline.scrape_video_list manual__2023-10-09T21:13:14.360072+00:00 [queued]>
[2023-10-09T21:13:19.007+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-09T21:13:19.049+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): scrape_video_list> on 2023-10-09 21:13:14.360072+00:00
[2023-10-09T21:13:19.069+0000] {standard_task_runner.py:57} INFO - Started process 257 to run task
[2023-10-09T21:13:19.085+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'youtube_data_pipeline', 'scrape_video_list', 'manual__2023-10-09T21:13:14.360072+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/youtube.py', '--cfg-path', '/tmp/tmpfx4r_ov5']
[2023-10-09T21:13:19.094+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask scrape_video_list
[2023-10-09T21:13:19.203+0000] {task_command.py:415} INFO - Running <TaskInstance: youtube_data_pipeline.scrape_video_list manual__2023-10-09T21:13:14.360072+00:00 [running]> on host 4e554196f202
[2023-10-09T21:13:19.388+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MSc DS-7029-20275335' AIRFLOW_CTX_DAG_ID='youtube_data_pipeline' AIRFLOW_CTX_TASK_ID='scrape_video_list' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T21:13:14.360072+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-09T21:13:14.360072+00:00'
[2023-10-09T21:13:19.395+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/youtube.py", line 103, in scrape_video_list
    print(unique_url_list)
UnboundLocalError: local variable 'unique_url_list' referenced before assignment
[2023-10-09T21:13:19.435+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_data_pipeline, task_id=scrape_video_list, execution_date=20231009T211314, start_date=20231009T211318, end_date=20231009T211319
[2023-10-09T21:13:19.472+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task scrape_video_list (local variable 'unique_url_list' referenced before assignment; 257)
[2023-10-09T21:13:19.545+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-09T21:13:19.613+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
